os: linux
dist: focal
language: python
env: 
  - COSIGN_EXPERIMENTAL=1
services:
  - docker
jobs:
  include:
    - stage: "sleep 109"
      script:
        - cosign version
        - echo arthanaharidas
        - docker login -u "damian0519" -p "${DOCKER_HUB_PASSWORD}"
        - docker build -t hello-world-python .
        - docker tag hello-world-python damian0519/python-hello-world
        - docker push damian0519/python-hello-world
        - export COSIGN_PASSWORD="${COS_PASSWORD}"
        - yes | cosign sign --key cosign.key damian0519/python-hello-world
        - cosign verify --key cosign.pub damian0519/python-hello-world
        - docker logout
 
keys:
  - KEY
